server:
  port: 8899

spring:
  profiles.active: dev # dev 、test、prod

  jackson:
    default-property-inclusion: non_null
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  servlet:
    multipart:
      max-file-size: 200MB
      max-request-size: 200MB

  datasource:
    initialSize: 5
    minIdle: 5
    maxActive: 20
    maxWait: 60000
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: SELECT 1 FROM DUAL
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: false
    filters: stat,wall,log4j
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000

  druid:
    web-stat-filter:
      enabled: true
      url-pattern: /*
    stat-view-servlet:
      enabled: true
      url-pattern: /druid/*
  #  redis配置
  redis:
    #    database: 0
    host: 192.168.0.110
    port: 6379
    password: redis@45
    jedis:
      pool:
        max-active: 200
        max-wait: -1
        max-idle: 10
        min-idle: 0
    timeout: 1000

mybatis-plus:
  # 如果是放在src/main/java目录下 classpath:/com/yourpackage/*/mapper/*Mapper.xml
  # 如果是放在resource目录 classpath:/mapper/*Mapper.xml
  mapper-locations: classpath:/basebus/*Mapper.xml,classpath:/mapper/*Mapper.xml
  #实体扫描，多个package用逗号或者分号分隔
  typeAliasesPackage: com.zhangshuo.basebus.model,com.zhangshuo.autotest.model
  global-config:
    #主键类型  0:数据库ID自增, 1:用户输入ID,2:全局唯一ID (数字类型唯一ID), 3:全局唯一ID UUID;
    id-type: 5
    #字段策略 0:忽略判断,1:非 NULL 判断),2:非空判断
    field-strategy: 1
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
    #配置JdbcTypeForNull
    jdbc-type-for-null: 'null'

admin:
  username: admin
  password: admin
  nicknname: 管理员

logging:
  config: classpath:logback-spring.xml